### ISSUE TITLE
Standard Library Modules: bogus error C2504: `'std::filesystem::_Dir_enum_impl'`: base class undefined

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3333]
On Discord, @davidhunter22 provided the following test case which is *very* similar to #3330, but which isn't helped by @fsb4000's workaround #3331:

```
D:\GitHub\STL\out\x64>type woof.cpp
```
```cpp
import std;

int main() {
    std::filesystem::directory_iterator x{"."};
}
```
```
D:\GitHub\STL\out\x64>cl /EHsc /nologo /W4 /std:c++latest /MTd /Od out\modules\std.ixx woof.cpp /Fewoof.exe
std.ixx
woof.cpp
woof.cpp(5): error C2504: 'std::filesystem::_Dir_enum_impl': base class undefined
Generating Code...
```

I was unable to work around this by adding `_EXPORT_STD` and/or `extern "C++"`, so it appears that we need to report an additional compiler bug beyond DevCom-10247495.

**Comment by StephanTLavavej** [comment]
Reported internally as VSO-1715231 "Standard Library Modules: Bogus error C2504: `'std::filesystem::_Dir_enum_impl'`: base class undefined".

**Comment by huangqinjin** [comment]
I also reported C2504 long time ago in [DevCom-10091963](https://developercommunity.visualstudio.com/t/10091963). No idea if they are same issue.

**Comment by StephanTLavavej** [comment]
This compiler bug has been fixed for VS 2022 17.6 Preview 2. :tada:

**Comment by ChemistAion** [comment]
It still appears for `std::filesystem::is_empty(...)`

Microsoft Visual Studio Community 2022
Version 17.5.0 Preview 6.0

**Comment by fsb4000** [comment]
@ChemistAion 

17.6 Preview 2 > 17.5 Preview 6

17.6 Preview 2 has not been released yet

**Comment by ChemistAion** [comment]
Yep, I get it... that part that I am missing with these :hooray: reacts above (yours included) - so we are celebrating fix of a regression bug in std::filesystem in VS that is not available yet?

**Comment by fsb4000** [comment]
Yeah, we like emojis and celebrating anything  😺 🎉

**Comment by ChemistAion** [comment]
ack, I joined :rabbit:
